---
title: Transforming Rotherham
timezone: Europe/London
description: Styles and assets for Transforming Rotherham

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
